# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='projects_img', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Заработок в интернете',
                'verbose_name_plural': 'Заработок в интернете',
            },
        ),
        migrations.CreateModel(
            name='ReferralUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='Идентификатор пользователя')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('username', models.CharField(blank=True, default='', max_length=100, verbose_name='Телеграм username')),
                ('refer_code', models.CharField(db_index=True, max_length=30, verbose_name='Хэш для реферальной ссылки')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Баланс')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='bot.ReferralUser', verbose_name='Пригласивший пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='На данный адрес будет отправляться информация о новых заказах', max_length=254, verbose_name='Е-mail адрес')),
                ('referrals_description', models.TextField(blank=True, verbose_name='Текст описания на странице "Приглашенные друзья"')),
                ('order_text', models.TextField(blank=True, verbose_name='Текст выводимый при нажатии на кнопку Заказать')),
                ('telegram', models.ForeignKey(help_text='На данный адрес будет отправляться информация о новых заказах', on_delete=django.db.models.deletion.CASCADE, to='bot.ReferralUser', verbose_name='Телеграмм аккаунт')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
